channels:
- conda-forge
- nodefaults
dependencies:
- python==3.12.*
- cartopy
- cftime
- imageio
- ipykernel
- jupyter
- jupyterlab
- metpy
- matplotlib
- netcdf4
- numpy
- uxarray
- xarray
- pip

name: dcmip2025